const { initDb, run, get, all } = require('./db');

// 单词数据格式: [word, translation, phonetic, example, exampleTranslation, difficulty, listType]
const words = [
  // ======= 初中高频词 (约300词) - 标记为 middle =======
  ["the", "这；那", "ðə", "The sun is bright.", "太阳很亮。", 1, "middle"],
  ["be", "是；在", "biː", "I will be there.", "我会在那。", 1, "middle"],
  ["have", "有", "hæv", "I have a book.", "我有一本书。", 1, "middle"],
  ["do", "做", "duː", "Do your homework.", "做你的作业。", 1, "middle"],
  ["say", "说", "seɪ", "Say it again.", "再说一次。", 1, "middle"],
  ["go", "去", "ɡoʊ", "Go to school.", "去上学。", 1, "middle"],
  ["get", "得到", "ɡet", "Get the ball.", "拿到球。", 1, "middle"],
  ["make", "做；制作", "meɪk", "Make a cake.", "做一个蛋糕。", 1, "middle"],
  ["know", "知道", "noʊ", "I know the answer.", "我知道答案。", 1, "middle"],
  ["think", "认为；思考", "θɪŋk", "Think about it.", "想一想。", 1, "middle"],
  ["take", "拿；带走", "teɪk", "Take a seat.", "请坐。", 1, "middle"],
  ["see", "看见", "siː", "I see a bird.", "我看到一只鸟。", 1, "middle"],
  ["come", "来", "kʌm", "Come here.", "过来。", 1, "middle"],
  ["want", "想要", "wɒnt", "I want water.", "我想要水。", 1, "middle"],
  ["give", "给", "ɡɪv", "Give me a pen.", "给我一支笔。", 1, "middle"],
  ["use", "使用", "juːz", "Use your head.", "动动脑筋。", 1, "middle"],
  ["find", "找到", "faɪnd", "Find the key.", "找到钥匙。", 1, "middle"],
  ["tell", "告诉", "tel", "Tell me a story.", "给我讲个故事。", 1, "middle"],
  ["ask", "问", "æsk", "Ask a question.", "问一个问题。", 1, "middle"],
  ["work", "工作；起作用", "wɜːrk", "I work hard.", "我努力工作。", 1, "middle"],
  ["seem", "似乎", "siːm", "It seems good.", "看起来不错。", 1, "middle"],
  ["feel", "感觉", "fiːl", "I feel happy.", "我感觉开心。", 1, "middle"],
  ["try", "尝试", "traɪ", "Try your best.", "尽力而为。", 1, "middle"],
  ["leave", "离开", "liːv", "Leave the room.", "离开房间。", 1, "middle"],
  ["call", "叫；打电话", "kɔːl", "Call me later.", "晚点打给我。", 1, "middle"],
  ["keep", "保持", "kiːp", "Keep quiet.", "保持安静。", 1, "middle"],
  ["let", "让", "let", "Let me see.", "让我看看。", 1, "middle"],
  ["begin", "开始", "bɪˈɡɪn", "Begin now.", "现在开始。", 1, "middle"],
  ["show", "展示", "ʃoʊ", "Show me the way.", "给我指路。", 1, "middle"],
  ["hear", "听到", "hɪr", "Hear the music.", "听到音乐。", 1, "middle"],
  ["play", "玩；播放", "pleɪ", "Play football.", "踢足球。", 1, "middle"],
  ["run", "跑", "rʌn", "Run fast.", "快跑。", 1, "middle"],
  ["move", "移动", "muːv", "Move closer.", "靠近点。", 1, "middle"],
  ["live", "居住；生活", "lɪv", "I live in Beijing.", "我住在北京。", 1, "middle"],
  ["believe", "相信", "bɪˈliːv", "I believe you.", "我相信你。", 1, "middle"],
  ["bring", "带来", "brɪŋ", "Bring your book.", "带上你的书。", 1, "middle"],
  ["happen", "发生", "ˈhæpən", "What happened?", "发生了什么？", 1, "middle"],
  ["write", "写", "raɪt", "Write a letter.", "写一封信。", 1, "middle"],
  ["read", "阅读", "riːd", "Read the book.", "读这本书。", 1, "middle"],
  ["speak", "说；讲", "spiːk", "Speak English.", "说英语。", 1, "middle"],
  ["study", "学习", "ˈstʌdi", "Study hard.", "努力学习。", 1, "middle"],
  ["learn", "学会", "lɜːrn", "Learn new words.", "学新单词。", 1, "middle"],
  ["teach", "教", "tiːtʃ", "Teach me English.", "教我英语。", 1, "middle"],
  ["help", "帮助", "help", "Help me.", "帮我。", 1, "middle"],
  ["like", "喜欢", "laɪk", "I like music.", "我喜欢音乐。", 1, "middle"],
  ["love", "爱", "lʌv", "Love your life.", "热爱生活。", 1, "middle"],
  ["hope", "希望", "hoʊp", "I hope so.", "我希望如此。", 1, "middle"],
  ["need", "需要", "niːd", "I need help.", "我需要帮助。", 1, "middle"],
  ["open", "打开", "ˈoʊpən", "Open the door.", "开门。", 1, "middle"],
  ["close", "关闭", "kloʊz", "Close the window.", "关窗。", 1, "middle"],
  ["start", "开始", "stɑːrt", "Start now.", "现在开始。", 1, "middle"],
  ["stop", "停止", "stɒp", "Stop talking.", "别说话了。", 1, "middle"],
  ["wait", "等待", "weɪt", "Wait for me.", "等我。", 1, "middle"],
  ["turn", "转动；转变", "tɜːrn", "Turn left.", "左转。", 1, "middle"],
  ["walk", "走；散步", "wɔːk", "Walk slowly.", "慢慢走。", 1, "middle"],
  ["talk", "谈话", "tɔːk", "Talk to me.", "跟我聊聊。", 1, "middle"],
  ["answer", "回答", "ˈænsər", "Answer the question.", "回答问题。", 1, "middle"],
  ["ask", "问；请求", "æsk", "Ask for help.", "请求帮助。", 1, "middle"],
  ["catch", "抓住", "kætʃ", "Catch the ball.", "接住球。", 1, "middle"],
  ["choose", "选择", "tʃuːz", "Choose one.", "选一个。", 1, "middle"],
  ["clean", "打扫；干净的", "kliːn", "Clean the room.", "打扫房间。", 1, "middle"],
  ["climb", "爬", "klaɪm", "Climb the tree.", "爬树。", 1, "middle"],
  ["cook", "做饭", "kʊk", "Cook dinner.", "做晚饭。", 1, "middle"],
  ["cross", "穿过", "krɔːs", "Cross the road.", "过马路。", 1, "middle"],
  ["dance", "跳舞", "dæns", "Dance with me.", "跟我跳舞。", 1, "middle"],
  ["draw", "画", "drɔː", "Draw a picture.", "画一幅画。", 1, "middle"],
  ["drink", "喝", "drɪŋk", "Drink water.", "喝水。", 1, "middle"],
  ["drive", "驾驶", "draɪv", "Drive carefully.", "小心驾驶。", 1, "middle"],
  ["eat", "吃", "iːt", "Eat breakfast.", "吃早餐。", 1, "middle"],
  ["enjoy", "享受", "ɪnˈdʒɔɪ", "Enjoy the show.", "享受表演。", 1, "middle"],
  ["enter", "进入", "ˈentər", "Enter the room.", "进入房间。", 1, "middle"],
  ["fall", "落下", "fɔːl", "Fall down.", "摔倒。", 1, "middle"],
  ["finish", "完成", "ˈfɪnɪʃ", "Finish your work.", "完成工作。", 1, "middle"],
  ["fly", "飞", "flaɪ", "Birds fly.", "鸟会飞。", 1, "middle"],
  ["follow", "跟随", "ˈfɒloʊ", "Follow me.", "跟我来。", 1, "middle"],
  ["forget", "忘记", "fərˈɡet", "Don't forget.", "别忘了。", 1, "middle"],
  ["grow", "成长；种植", "ɡroʊ", "Grow up.", "长大。", 1, "middle"],
  ["guess", "猜", "ɡes", "Guess what?", "猜猜看？", 1, "middle"],
  ["hate", "讨厌", "heɪt", "I hate it.", "我讨厌它。", 1, "middle"],
  ["hide", "躲藏", "haɪd", "Hide behind me.", "躲在我后面。", 1, "middle"],
  ["hit", "打；撞", "hɪt", "Hit the ball.", "击球。", 1, "middle"],
  ["hold", "握住；举行", "hoʊld", "Hold my hand.", "握住我的手。", 1, "middle"],
  ["hurt", "受伤；疼", "hɜːrt", "My leg hurts.", "我的腿疼。", 1, "middle"],
  ["join", "加入", "dʒɔɪn", "Join us.", "加入我们。", 1, "middle"],
  ["jump", "跳", "dʒʌmp", "Jump high.", "跳高。", 1, "middle"],
  ["kick", "踢", "kɪk", "Kick the ball.", "踢球。", 1, "middle"],
  ["kill", "杀", "kɪl", "Don't kill it.", "别杀它。", 1, "middle"],
  ["kiss", "亲吻", "kɪs", "Kiss me.", "亲我。", 1, "middle"],
  ["laugh", "笑", "læf", "Laugh out loud.", "大笑。", 1, "middle"],
  ["lie", "躺；说谎", "laɪ", "Lie down.", "躺下。", 1, "middle"],
  ["lift", "举起", "lɪft", "Lift the box.", "举起箱子。", 1, "middle"],
  ["listen", "听", "ˈlɪsn", "Listen carefully.", "仔细听。", 1, "middle"],
  ["look", "看", "lʊk", "Look at me.", "看着我。", 1, "middle"],
  ["lose", "失去；输", "luːz", "Lose the game.", "输了比赛。", 1, "middle"],
  ["mark", "标记", "mɑːrk", "Mark the place.", "标记这个地方。", 1, "middle"],
  ["mean", "意思是", "miːn", "What does it mean?", "它是什么意思？", 1, "middle"],
  ["meet", "遇见", "miːt", "Nice to meet you.", "很高兴认识你。", 1, "middle"],
  ["miss", "想念；错过", "mɪs", "I miss you.", "我想你。", 1, "middle"],
  ["pass", "通过；传递", "pæs", "Pass the exam.", "通过考试。", 1, "middle"],
  ["pay", "支付", "peɪ", "Pay the bill.", "付账。", 1, "middle"],
  ["pick", "捡起；挑选", "pɪk", "Pick it up.", "捡起来。", 1, "middle"],
  ["plant", "种植", "plænt", "Plant a tree.", "种一棵树。", 1, "middle"],
  ["pull", "拉", "pʊl", "Pull the door.", "拉门。", 1, "middle"],
  ["push", "推", "pʊʃ", "Push the button.", "按按钮。", 1, "middle"],
  ["put", "放", "pʊt", "Put it down.", "放下来。", 1, "middle"],
  ["raise", "举起；提高", "reɪz", "Raise your hand.", "举手。", 1, "middle"],
  ["reach", "到达；够到", "riːtʃ", "Reach the top.", "到达顶点。", 1, "middle"],
  ["remember", "记住", "rɪˈmembər", "Remember this.", "记住这个。", 1, "middle"],
  ["return", "返回；归还", "rɪˈtɜːrn", "Return home.", "回家。", 1, "middle"],
  ["ride", "骑", "raɪd", "Ride a bike.", "骑自行车。", 1, "middle"],
  ["ring", "响；打电话", "rɪŋ", "The bell rings.", "铃响了。", 1, "middle"],
  ["rob", "抢劫", "rɒb", "They rob the bank.", "他们抢银行。", 1, "middle"],
  ["save", "拯救；节省", "seɪv", "Save the world.", "拯救世界。", 1, "middle"],
  ["sell", "卖", "sel", "Sell the car.", "卖车。", 1, "middle"],
  ["send", "发送", "send", "Send a message.", "发消息。", 1, "middle"],
  ["set", "设置；放置", "set", "Set the table.", "摆桌子。", 1, "middle"],
  ["shake", "摇晃", "ʃeɪk", "Shake hands.", "握手。", 1, "middle"],
  ["shoot", "射击", "ʃuːt", "Shoot the ball.", "投篮。", 1, "middle"],
  ["shout", "喊叫", "ʃaʊt", "Shout for help.", "大声呼救。", 1, "middle"],
  ["sing", "唱歌", "sɪŋ", "Sing a song.", "唱首歌。", 1, "middle"],
  ["sit", "坐", "sɪt", "Sit down.", "坐下。", 1, "middle"],
  ["sleep", "睡觉", "sliːp", "Sleep well.", "睡个好觉。", 1, "middle"],
  ["smell", "闻", "smel", "Smell the flower.", "闻闻花。", 1, "middle"],
  ["smile", "微笑", "smaɪl", "Smile at me.", "对我微笑。", 1, "middle"],
  ["spend", "花费", "spend", "Spend money.", "花钱。", 1, "middle"],
  ["stand", "站", "stænd", "Stand up.", "站起来。", 1, "middle"],
  ["steal", "偷", "stiːl", "Don't steal.", "别偷东西。", 1, "middle"],
  ["swim", "游泳", "swɪm", "Swim fast.", "游得快。", 1, "middle"],
  ["throw", "扔", "θroʊ", "Throw the ball.", "扔球。", 1, "middle"],
  ["touch", "触摸", "tʌtʃ", "Don't touch.", "别碰。", 1, "middle"],
  ["travel", "旅行", "ˈtrævl", "Travel around.", "到处旅行。", 1, "middle"],
  ["understand", "理解", "ˌʌndərˈstænd", "I understand.", "我理解。", 1, "middle"],
  ["visit", "拜访", "ˈvɪzɪt", "Visit a friend.", "拜访朋友。", 1, "middle"],
  ["wait", "等", "weɪt", "Wait a moment.", "等一下。", 1, "middle"],
  ["wake", "醒", "weɪk", "Wake up.", "醒来。", 1, "middle"],
  ["wash", "洗", "wɒʃ", "Wash your hands.", "洗手。", 1, "middle"],
  ["watch", "看", "wɒtʃ", "Watch TV.", "看电视。", 1, "middle"],
  ["wear", "穿", "wer", "Wear a coat.", "穿外套。", 1, "middle"],
  ["win", "赢", "wɪn", "Win the game.", "赢得比赛。", 1, "middle"],
  ["wish", "祝愿", "wɪʃ", "Wish you luck.", "祝你好运。", 1, "middle"],
  ["worry", "担心", "ˈwɜːri", "Don't worry.", "别担心。", 1, "middle"],
  ["agree", "同意", "əˈɡriː", "I agree.", "我同意。", 1, "middle"],
  ["allow", "允许", "əˈlaʊ", "Allow me.", "允许我。", 1, "middle"],
  ["appear", "出现", "əˈpɪr", "He appears.", "他出现了。", 1, "middle"],
  ["arrive", "到达", "əˈraɪv", "Arrive on time.", "准时到达。", 1, "middle"],
  ["become", "成为", "bɪˈkʌm", "Become better.", "变得更好。", 1, "middle"],
  ["borrow", "借入", "ˈbɒroʊ", "Borrow a book.", "借一本书。", 1, "middle"],
  ["break", "打破", "breɪk", "Break the glass.", "打破玻璃。", 1, "middle"],
  ["build", "建造", "bɪld", "Build a house.", "建房子。", 1, "middle"],
  ["buy", "买", "baɪ", "Buy some food.", "买点吃的。", 1, "middle"],
  ["care", "关心", "ker", "Care about others.", "关心他人。", 1, "middle"],
  ["carry", "搬运", "ˈkæri", "Carry the bag.", "背包。", 1, "middle"],
  ["cause", "导致", "kɔːz", "Cause trouble.", "惹麻烦。", 1, "middle"],
  ["celebrate", "庆祝", "ˈselɪbreɪt", "Celebrate the holiday.", "庆祝节日。", 1, "middle"],
  ["change", "改变", "tʃeɪndʒ", "Change your mind.", "改变主意。", 1, "middle"],
  ["check", "检查", "tʃek", "Check the answer.", "检查答案。", 1, "middle"],
  ["cheer", "欢呼", "tʃɪr", "Cheer up!", "振作起来！", 1, "middle"],
  ["collect", "收集", "kəˈlekt", "Collect stamps.", "集邮。", 1, "middle"],
  ["compare", "比较", "kəmˈper", "Compare them.", "比较它们。", 1, "middle"],
  ["compete", "竞争", "kəmˈpiːt", "Compete fairly.", "公平竞争。", 1, "middle"],
  ["complete", "完成", "kəmˈpliːt", "Complete the task.", "完成任务。", 1, "middle"],
  ["connect", "连接", "kəˈnekt", "Connect online.", "在线连接。", 1, "middle"],
  ["consider", "考虑", "kənˈsɪdər", "Consider this.", "考虑这个。", 1, "middle"],
  ["continue", "继续", "kənˈtɪnjuː", "Continue learning.", "继续学习。", 1, "middle"],
  ["control", "控制", "kənˈtroʊl", "Control yourself.", "控制自己。", 1, "middle"],
  ["count", "数数", "kaʊnt", "Count to ten.", "数到十。", 1, "middle"],
  ["cover", "覆盖", "ˈkʌvər", "Cover the table.", "盖住桌子。", 1, "middle"],
  ["create", "创造", "kriˈeɪt", "Create art.", "创造艺术。", 1, "middle"],
  ["cry", "哭", "kraɪ", "Don't cry.", "别哭。", 1, "middle"],
  ["decide", "决定", "dɪˈsaɪd", "Decide now.", "现在决定。", 1, "middle"],
  ["describe", "描述", "dɪˈskraɪb", "Describe it.", "描述它。", 1, "middle"],
  ["develop", "发展", "dɪˈveləp", "Develop skills.", "发展技能。", 1, "middle"],
  ["discover", "发现", "dɪˈskʌvər", "Discover new things.", "发现新事物。", 1, "middle"],
  ["discuss", "讨论", "dɪˈskʌs", "Discuss the plan.", "讨论计划。", 1, "middle"],
  ["divide", "分开", "dɪˈvaɪd", "Divide into groups.", "分成小组。", 1, "middle"],
  ["doubt", "怀疑", "daʊt", "I doubt it.", "我怀疑。", 1, "middle"],
  ["dream", "梦想", "driːm", "Dream big.", "胸怀大志。", 1, "middle"],
  ["drop", "掉下；放弃", "drɒp", "Drop the plan.", "放弃计划。", 1, "middle"],
  ["end", "结束", "end", "End the game.", "结束比赛。", 1, "middle"],
  ["expect", "期待", "ɪkˈspekt", "Expect the best.", "期待最好的。", 1, "middle"],
  ["explain", "解释", "ɪkˈspleɪn", "Explain it to me.", "给我解释一下。", 1, "middle"],
  ["fail", "失败", "feɪl", "Don't give up.", "不要放弃。", 1, "middle"],
  ["fight", "打斗；奋斗", "faɪt", "Fight for your dream.", "为梦想而战。", 1, "middle"],
  ["fill", "填满", "fɪl", "Fill the cup.", "倒满杯子。", 1, "middle"],
  ["fit", "适合", "fɪt", "It fits you.", "它适合你。", 1, "middle"],
  ["fix", "修理", "fɪks", "Fix the bike.", "修自行车。", 1, "middle"],
  ["force", "强迫", "fɔːrs", "Don't force me.", "别强迫我。", 1, "middle"],
  ["form", "形成", "fɔːrm", "Form a habit.", "养成习惯。", 1, "middle"],
  ["free", "自由；免费", "friː", "Free time.", "空闲时间。", 1, "middle"],
  ["friendly", "友好的", "ˈfrendli", "Be friendly.", "友好一点。", 1, "middle"],
  ["frighten", "害怕", "ˈfraɪtn", "Don't be frightened.", "别害怕。", 1, "middle"],
  ["fun", "乐趣", "fʌn", "Have fun!", "玩得开心！", 1, "middle"],
  ["future", "未来", "ˈfjuːtʃər", "Future life.", "未来的生活。", 1, "middle"],
  ["gentle", "温柔的", "ˈdʒentl", "Be gentle.", "温柔点。", 1, "middle"],
  ["glad", "高兴的", "ɡlæd", "I'm glad.", "我很高兴。", 1, "middle"],
  ["gold", "金子；金色", "ɡoʊld", "Gold medal.", "金牌。", 1, "middle"],
  ["guest", "客人", "ɡest", "Welcome guest.", "欢迎客人。", 1, "middle"],
  ["habit", "习惯", "ˈhæbɪt", "Good habit.", "好习惯。", 1, "middle"],
  ["half", "一半", "hæf", "Half an hour.", "半小时。", 1, "middle"],
  ["handsome", "英俊的", "ˈhænsəm", "Handsome boy.", "英俊的男孩。", 1, "middle"],
  ["happy", "快乐的", "ˈhæpi", "Happy birthday!", "生日快乐！", 1, "middle"],
  ["hard", "困难的；努力地", "hɑːrd", "Hard work.", "努力工作。", 1, "middle"],
  ["healthy", "健康的", "ˈhelθi", "Stay healthy.", "保持健康。", 1, "middle"],
  ["heavy", "重的", "ˈhevi", "Heavy rain.", "大雨。", 1, "middle"],
  ["honest", "诚实的", "ˈɒnɪst", "Be honest.", "要诚实。", 1, "middle"],
  ["hungry", "饿的", "ˈhʌŋɡri", "I'm hungry.", "我饿了。", 1, "middle"],
  ["important", "重要的", "ɪmˈpɔːrtnt", "Important thing.", "重要的事。", 1, "middle"],
  ["interesting", "有趣的", "ˈɪntrəstɪŋ", "Interesting book.", "有趣的书。", 1, "middle"],
  ["kind", "善良的；种类", "kaɪnd", "Kind heart.", "善良的心。", 1, "middle"],
  ["lazy", "懒惰的", "ˈleɪzi", "Don't be lazy.", "别偷懒。", 1, "middle"],
  ["lonely", "孤独的", "ˈloʊnli", "Feel lonely.", "感到孤独。", 1, "middle"],
  ["lovely", "可爱的", "ˈlʌvli", "Lovely girl.", "可爱的女孩。", 1, "middle"],
  ["lucky", "幸运的", "ˈlʌki", "Lucky day.", "幸运的一天。", 1, "middle"],
  ["modern", "现代的", "ˈmɒdərn", "Modern city.", "现代城市。", 1, "middle"],
  ["narrow", "狭窄的", "ˈnæroʊ", "Narrow road.", "狭窄的路。", 1, "middle"],
  ["necessary", "必要的", "ˈnesəseri", "It's necessary.", "这是必要的。", 1, "middle"],
  ["nervous", "紧张的", "ˈnɜːrvəs", "Feel nervous.", "感到紧张。", 1, "middle"],
  ["normal", "正常的", "ˈnɔːrml", "Normal life.", "正常的生活。", 1, "middle"],
  ["popular", "流行的", "ˈpɒpjələr", "Popular song.", "流行歌曲。", 1, "middle"],
  ["possible", "可能的", "ˈpɒsəbl", "It's possible.", "这是可能的。", 1, "middle"],
  ["proper", "适当的", "ˈprɒpər", "Proper way.", "适当的方式。", 1, "middle"],
  ["proud", "自豪的", "praʊd", "Proud of you.", "为你骄傲。", 1, "middle"],
  ["quiet", "安静的", "ˈkwaɪət", "Keep quiet.", "保持安静。", 1, "middle"],
  ["ready", "准备好的", "ˈredi", "Get ready.", "准备好。", 1, "middle"],
  ["rich", "富有的", "rɪtʃ", "Rich man.", "富人。", 1, "middle"],
  ["rude", "粗鲁的", "ruːd", "Don't be rude.", "别粗鲁。", 1, "middle"],
  ["safe", "安全的", "seɪf", "Safe place.", "安全的地方。", 1, "middle"],
  ["shy", "害羞的", "ʃaɪ", "Shy girl.", "害羞的女孩。", 1, "middle"],
  ["silly", "愚蠢的", "ˈsɪli", "Silly idea.", "愚蠢的主意。", 1, "middle"],
  ["simple", "简单的", "ˈsɪmpl", "Simple life.", "简单的生活。", 1, "middle"],
  ["sorry", "抱歉的", "ˈsɒri", "I'm sorry.", "对不起。", 1, "middle"],
  ["stupid", "笨的", "ˈstuːpɪd", "Stupid mistake.", "愚蠢的错误。", 1, "middle"],
  ["suitable", "合适的", "ˈsuːtəbl", "Suitable time.", "合适的时间。", 1, "middle"],
  ["sure", "确定的", "ʃʊr", "I'm sure.", "我确定。", 1, "middle"],
  ["surprised", "惊讶的", "sərˈpraɪzd", "Surprised look.", "惊讶的表情。", 1, "middle"],
  ["terrible", "可怕的", "ˈterəbl", "Terrible day.", "糟糕的一天。", 1, "middle"],
  ["thirsty", "渴的", "ˈθɜːrsti", "I'm thirsty.", "我渴了。", 1, "middle"],
  ["tiny", "微小的", "ˈtaɪni", "Tiny house.", "小房子。", 1, "middle"],
  ["tired", "累的", "ˈtaɪərd", "I'm tired.", "我累了。", 1, "middle"],
  ["useful", "有用的", "ˈjuːsfəl", "Useful tool.", "有用的工具。", 1, "middle"],
  ["valuable", "有价值的", "ˈvæljuəbl", "Valuable lesson.", "宝贵的教训。", 1, "middle"],
  ["weak", "弱的", "wiːk", "Weak point.", "弱点。", 1, "middle"],
  ["whole", "整个的", "hoʊl", "The whole day.", "一整天。", 1, "middle"],
  ["wise", "明智的", "waɪz", "Wise decision.", "明智的决定。", 1, "middle"],
  ["wonderful", "精彩的", "ˈwʌndərfl", "Wonderful day.", "精彩的一天。", 1, "middle"],
  ["wrong", "错误的", "rɔːŋ", "Wrong answer.", "错误的答案。", 1, "middle"],
  ["young", "年轻的", "jʌŋ", "Young people.", "年轻人。", 1, "middle"],
  ["across", "穿过；对面", "əˈkrɔːs", "Across the street.", "穿过街道。", 1, "middle"],
  ["always", "总是", "ˈɔːlweɪz", "Always remember.", "永远记得。", 1, "middle"],
  ["never", "从不", "ˈnevər", "Never give up.", "永不放弃。", 1, "middle"],
  ["often", "经常", "ˈɔːfən", "Often late.", "经常迟到。", 1, "middle"],
  ["seldom", "很少", "ˈseldəm", "Seldom go out.", "很少出门。", 1, "middle"],
  ["sometimes", "有时", "ˈsʌmtaɪmz", "Sometimes I cry.", "有时我哭。", 1, "middle"],
  ["usually", "通常", "ˈjuːʒuəli", "Usually get up early.", "通常早起。", 1, "middle"],
  ["already", "已经", "ɔːlˈredi", "Already done.", "已经完成了。", 1, "middle"],
  ["just", "刚刚；仅仅", "dʒʌst", "Just now.", "刚刚。", 1, "middle"],
  ["still", "仍然", "stɪl", "Still waiting.", "仍在等待。", 1, "middle"],
  ["yet", "还；已经", "jet", "Not yet.", "还没有。", 1, "middle"],
  ["again", "再次", "əˈɡen", "Try again.", "再试一次。", 1, "middle"],
  ["almost", "几乎", "ˈɔːlmoʊst", "Almost there.", "快到了。", 1, "middle"],
  ["enough", "足够", "ɪˈnʌf", "Enough sleep.", "充足的睡眠。", 1, "middle"],
  ["quite", "相当", "kwaɪt", "Quite good.", "相当好。", 1, "middle"],
  ["rather", "相当；宁愿", "ˈræðər", "Rather tired.", "相当累。", 1, "middle"],
  ["very", "非常", "ˈveri", "Very good.", "非常好。", 1, "middle"],
  ["too", "太；也", "tuː", "Too much.", "太多。", 1, "middle"],
  ["also", "也", "ˈɔːlsoʊ", "Also like it.", "也喜欢它。", 1, "middle"],
  ["either", "也（否定）", "ˈaɪðər", "Not good either.", "也不好。", 1, "middle"],
  ["neither", "两者都不", "ˈnaɪðər", "Neither of them.", "他们两个都不。", 1, "middle"],
  ["once", "曾经；一旦", "wʌns", "Once upon a time.", "从前。", 1, "middle"],

  // ======= 高考核心词汇 (约500词) =======
  ["abandon", "放弃；抛弃", "əˈbændən", "Never abandon hope.", "永不放弃希望。", 2, "gaokao"],
  ["ability", "能力", "əˈbɪləti", "Ability to learn.", "学习能力。", 2, "gaokao"],
  ["absorb", "吸收；吸引", "əbˈzɔːrb", "Absorb knowledge.", "吸收知识。", 2, "gaokao"],
  ["abstract", "抽象的", "ˈæbstrækt", "Abstract concept.", "抽象概念。", 3, "gaokao"],
  ["academic", "学术的", "ˌækəˈdemɪk", "Academic research.", "学术研究。", 2, "gaokao"],
  ["accelerate", "加速", "əkˈseləreɪt", "Accelerate progress.", "加速进步。", 3, "gaokao"],
  ["access", "进入；通道", "ˈækses", "Access the internet.", "上网。", 2, "gaokao"],
  ["accompany", "陪伴", "əˈkʌmpəni", "Accompany me.", "陪我。", 2, "gaokao"],
  ["accomplish", "完成；实现", "əˈkɑːmplɪʃ", "Accomplish the goal.", "实现目标。", 3, "gaokao"],
  ["accurate", "准确的", "ˈækjərət", "Accurate answer.", "准确的答案。", 2, "gaokao"],
  ["accuse", "指控", "əˈkjuːz", "Accuse him of lying.", "指控他撒谎。", 2, "gaokao"],
  ["achieve", "取得；实现", "əˈtʃiːv", "Achieve success.", "取得成功。", 2, "gaokao"],
  ["acknowledge", "承认", "əkˈnɒlɪdʒ", "Acknowledge mistake.", "承认错误。", 3, "gaokao"],
  ["acquire", "获得", "əˈkwaɪər", "Acquire knowledge.", "获取知识。", 2, "gaokao"],
  ["adapt", "适应", "əˈdæpt", "Adapt to changes.", "适应变化。", 2, "gaokao"],
  ["adequate", "充分的", "ˈædɪkwət", "Adequate preparation.", "充分准备。", 3, "gaokao"],
  ["adjust", "调整", "əˈdʒʌst", "Adjust the plan.", "调整计划。", 2, "gaokao"],
  ["admire", "钦佩", "ədˈmaɪər", "I admire you.", "我钦佩你。", 2, "gaokao"],
  ["admit", "承认", "ədˈmɪt", "Admit the truth.", "承认真相。", 2, "gaokao"],
  ["adopt", "采纳；收养", "əˈdɒpt", "Adopt a new method.", "采用新方法。", 2, "gaokao"],
  ["advance", "前进；进步", "ədˈvæns", "Advance in technology.", "技术进步。", 2, "gaokao"],
  ["advantage", "优势", "ədˈvæntɪdʒ", "Take advantage of.", "利用。", 2, "gaokao"],
  ["adventure", "冒险", "ədˈventʃər", "Great adventure.", "伟大的冒险。", 2, "gaokao"],
  ["affect", "影响", "əˈfekt", "Affect the result.", "影响结果。", 2, "gaokao"],
  ["afford", "负担得起", "əˈfɔːrd", "Can't afford it.", "负担不起。", 2, "gaokao"],
  ["agriculture", "农业", "ˈæɡrɪkʌltʃər", "Modern agriculture.", "现代农业。", 3, "gaokao"],
  ["allocate", "分配", "ˈæləkeɪt", "Allocate resources.", "分配资源。", 3, "gaokao"],
  ["alternative", "替代的", "ɔːlˈtɜːrnətɪv", "Alternative way.", "替代方法。", 2, "gaokao"],
  ["amaze", "使惊奇", "əˈmeɪz", "Amaze the world.", "让世界惊叹。", 2, "gaokao"],
  ["ambition", "雄心", "æmˈbɪʃn", "Great ambition.", "远大的抱负。", 2, "gaokao"],
  ["analyze", "分析", "ˈænəlaɪz", "Analyze the data.", "分析数据。", 2, "gaokao"],
  ["announce", "宣布", "əˈnaʊns", "Announce the news.", "宣布消息。", 2, "gaokao"],
  ["annual", "每年的", "ˈænjuəl", "Annual meeting.", "年会。", 2, "gaokao"],
  ["anxiety", "焦虑", "æŋˈzaɪəti", "Feel anxiety.", "感到焦虑。", 2, "gaokao"],
  ["apparent", "明显的", "əˈpærənt", "Apparent reason.", "明显的原因。", 3, "gaokao"],
  ["appeal", "吸引；呼吁", "əˈpiːl", "Appeal to young people.", "吸引年轻人。", 2, "gaokao"],
  ["apply", "申请；应用", "əˈplaɪ", "Apply for college.", "申请大学。", 2, "gaokao"],
  ["appoint", "任命", "əˈpɔɪnt", "Appoint a leader.", "任命领导。", 3, "gaokao"],
  ["appreciate", "感激；欣赏", "əˈpriːʃieɪt", "I appreciate your help.", "我感谢你的帮助。", 2, "gaokao"],
  ["approach", "接近；方法", "əˈproʊtʃ", "New approach.", "新方法。", 2, "gaokao"],
  ["appropriate", "适当的", "əˈproʊpriət", "Appropriate time.", "适当的时间。", 3, "gaokao"],
  ["approve", "批准", "əˈpruːv", "Approve the plan.", "批准计划。", 2, "gaokao"],
  ["argue", "争论", "ˈɑːrɡjuː", "Argue with him.", "和他争论。", 2, "gaokao"],
  ["arise", "出现；产生", "əˈraɪz", "Problems arise.", "问题出现。", 2, "gaokao"],
  ["arrange", "安排", "əˈreɪndʒ", "Arrange a meeting.", "安排会议。", 2, "gaokao"],
  ["article", "文章；物品", "ˈɑːrtɪkl", "Read an article.", "读一篇文章。", 2, "gaokao"],
  ["aspect", "方面", "ˈæspekt", "Every aspect.", "每个方面。", 2, "gaokao"],
  ["assess", "评估", "əˈses", "Assess the situation.", "评估形势。", 3, "gaokao"],
  ["assign", "分配；指定", "əˈsaɪn", "Assign homework.", "布置作业。", 2, "gaokao"],
  ["assist", "协助", "əˈsɪst", "Assist the teacher.", "协助老师。", 2, "gaokao"],
  ["associate", "联系；联想", "əˈsoʊʃieɪt", "Associate with friends.", "和朋友交往。", 2, "gaokao"],
  ["assume", "假设；承担", "əˈsuːm", "Assume responsibility.", "承担责任。", 2, "gaokao"],
  ["atmosphere", "气氛；大气", "ˈætməsfɪr", "Warm atmosphere.", "温暖的气氛。", 2, "gaokao"],
  ["attach", "附上；依恋", "əˈtætʃ", "Attach the file.", "附上文件。", 2, "gaokao"],
  ["attempt", "尝试", "əˈtempt", "Attempt the exam.", "尝试考试。", 2, "gaokao"],
  ["attend", "参加", "əˈtend", "Attend school.", "上学。", 2, "gaokao"],
  ["attitude", "态度", "ˈætɪtjuːd", "Positive attitude.", "积极的态度。", 2, "gaokao"],
  ["attract", "吸引", "əˈtrækt", "Attract attention.", "吸引注意力。", 2, "gaokao"],
  ["authority", "权威；当局", "ɔːˈθɒrəti", "School authorities.", "学校当局。", 3, "gaokao"],
  ["available", "可用的", "əˈveɪləbl", "Available resources.", "可用资源。", 2, "gaokao"],
  ["average", "平均的", "ˈævərɪdʒ", "Average score.", "平均分。", 2, "gaokao"],
  ["avoid", "避免", "əˈvɔɪd", "Avoid mistakes.", "避免错误。", 2, "gaokao"],
  ["aware", "意识到", "əˈwer", "Be aware of.", "意识到。", 2, "gaokao"],
  ["balance", "平衡", "ˈbæləns", "Keep balance.", "保持平衡。", 2, "gaokao"],
  ["barrier", "障碍", "ˈbæriər", "Language barrier.", "语言障碍。", 2, "gaokao"],
  ["behave", "表现", "bɪˈheɪv", "Behave well.", "表现良好。", 2, "gaokao"],
  ["benefit", "利益；受益", "ˈbenɪfɪt", "Benefit from reading.", "从阅读中受益。", 2, "gaokao"],
  ["blame", "责备", "bleɪm", "Don't blame me.", "别怪我。", 2, "gaokao"],
  ["bother", "打扰", "ˈbɒðər", "Don't bother.", "别打扰。", 2, "gaokao"],
  ["boundary", "边界", "ˈbaʊndəri", "Boundary line.", "边界线。", 3, "gaokao"],
  ["brilliant", "杰出的", "ˈbrɪliənt", "Brilliant idea.", "绝妙的主意。", 2, "gaokao"],
  ["budget", "预算", "ˈbʌdʒɪt", "Budget plan.", "预算计划。", 2, "gaokao"],
  ["burden", "负担", "ˈbɜːrdn", "Financial burden.", "经济负担。", 2, "gaokao"],
  ["calm", "冷静的", "kɑːm", "Keep calm.", "保持冷静。", 2, "gaokao"],
  ["campaign", "运动；活动", "kæmˈpeɪn", "Election campaign.", "选举活动。", 2, "gaokao"],
  ["capable", "有能力的", "ˈkeɪpəbl", "Capable person.", "有能力的人。", 2, "gaokao"],
  ["capacity", "容量；能力", "kəˈpæsəti", "Learning capacity.", "学习能力。", 3, "gaokao"],
  ["capture", "捕获", "ˈkæptʃər", "Capture the moment.", "捕捉瞬间。", 2, "gaokao"],
  ["career", "职业", "kəˈrɪr", "Career choice.", "职业选择。", 2, "gaokao"],
  ["challenge", "挑战", "ˈtʃælɪndʒ", "Face the challenge.", "面对挑战。", 2, "gaokao"],
  ["character", "性格；角色", "ˈkærəktər", "Main character.", "主角。", 2, "gaokao"],
  ["charity", "慈善", "ˈtʃærəti", "Charity work.", "慈善工作。", 2, "gaokao"],
  ["circumstance", "环境；情况", "ˈsɜːrkəmstæns", "Under any circumstance.", "在任何情况下。", 3, "gaokao"],
  ["civilization", "文明", "ˌsɪvələˈzeɪʃn", "Ancient civilization.", "古代文明。", 3, "gaokao"],
  ["clarify", "澄清", "ˈklærəfaɪ", "Clarify the issue.", "澄清问题。", 3, "gaokao"],
  ["classify", "分类", "ˈklæsɪfaɪ", "Classify the items.", "分类物品。", 3, "gaokao"],
  ["climate", "气候", "ˈklaɪmət", "Climate change.", "气候变化。", 2, "gaokao"],
  ["collapse", "崩溃；倒塌", "kəˈlæps", "Building collapses.", "大楼倒塌。", 2, "gaokao"],
  ["combine", "结合", "kəmˈbaɪn", "Combine theory with practice.", "理论与实践结合。", 2, "gaokao"],
  ["comment", "评论", "ˈkɒment", "Leave a comment.", "发表评论。", 2, "gaokao"],
  ["commit", "犯；承诺", "kəˈmɪt", "Commit a crime.", "犯罪。", 2, "gaokao"],
  ["communicate", "交流", "kəˈmjuːnɪkeɪt", "Communicate with others.", "与他人交流。", 2, "gaokao"],
  ["community", "社区", "kəˈmjuːnəti", "Local community.", "本地社区。", 2, "gaokao"],
  ["companion", "同伴", "kəmˈpæniən", "Travel companion.", "旅伴。", 2, "gaokao"],
  ["company", "公司；陪伴", "ˈkʌmpəni", "Keep company.", "陪伴。", 2, "gaokao"],
  ["compensate", "补偿", "ˈkɒmpenseɪt", "Compensate for loss.", "赔偿损失。", 3, "gaokao"],
  ["complain", "抱怨", "kəmˈpleɪn", "Complain about the service.", "抱怨服务。", 2, "gaokao"],
  ["complex", "复杂的", "kəmˈpleks", "Complex problem.", "复杂的问题。", 2, "gaokao"],
  ["compose", "组成；创作", "kəmˈpoʊz", "Compose a song.", "创作一首歌。", 3, "gaokao"],
  ["concentrate", "集中", "ˈkɒnsntreɪt", "Concentrate on study.", "集中学习。", 2, "gaokao"],
  ["concept", "概念", "ˈkɒnsept", "Key concept.", "关键概念。", 3, "gaokao"],
  ["concern", "关心；担忧", "kənˈsɜːrn", "Concern about health.", "关心健康。", 2, "gaokao"],
  ["conclude", "结论", "kənˈkluːd", "Conclude the meeting.", "结束会议。", 2, "gaokao"],
  ["condition", "条件；状况", "kənˈdɪʃn", "Living condition.", "生活条件。", 2, "gaokao"],
  ["confident", "自信的", "ˈkɒnfɪdənt", "Be confident.", "要自信。", 2, "gaokao"],
  ["confirm", "确认", "kənˈfɜːrm", "Confirm the booking.", "确认预订。", 2, "gaokao"],
  ["conflict", "冲突", "ˈkɒnflɪkt", "Conflict of interest.", "利益冲突。", 2, "gaokao"],
  ["confuse", "使困惑", "kənˈfjuːz", "Confuse the students.", "让学生困惑。", 2, "gaokao"],
  ["consequence", "结果", "ˈkɒnsɪkwens", "Face the consequences.", "面对后果。", 2, "gaokao"],
  ["conservation", "保护", "ˌkɒnsərˈveɪʃn", "Wildlife conservation.", "野生动物保护。", 3, "gaokao"],
  ["conservative", "保守的", "kənˈsɜːrvətɪv", "Conservative view.", "保守的观点。", 3, "gaokao"],
  ["considerable", "相当大的", "kənˈsɪdərəbl", "Considerable amount.", "相当大的数量。", 3, "gaokao"],
  ["consistent", "一致的", "kənˈsɪstənt", "Consistent effort.", "持续的努力。", 3, "gaokao"],
  ["constant", "不断的", "ˈkɒnstənt", "Constant change.", "不断变化。", 2, "gaokao"],
  ["construct", "建造", "kənˈstrʌkt", "Construct a bridge.", "建桥。", 2, "gaokao"],
  ["consult", "咨询", "kənˈsʌlt", "Consult a doctor.", "咨询医生。", 2, "gaokao"],
  ["consume", "消费", "kənˈsuːm", "Consume energy.", "消耗能量。", 2, "gaokao"],
  ["contact", "联系", "ˈkɒntækt", "Contact me later.", "稍后联系我。", 2, "gaokao"],
  ["contemporary", "当代的", "kənˈtempəreri", "Contemporary art.", "当代艺术。", 3, "gaokao"],
  ["content", "内容；满意的", "ˈkɒntent", "Table of contents.", "目录。", 2, "gaokao"],
  ["contest", "比赛", "ˈkɒntest", "Speech contest.", "演讲比赛。", 2, "gaokao"],
  ["contribute", "贡献", "kənˈtrɪbjuːt", "Contribute to society.", "为社会做贡献。", 2, "gaokao"],
  ["controversial", "有争议的", "ˌkɒntrəˈvɜːrʃl", "Controversial issue.", "有争议的问题。", 3, "gaokao"],
  ["convenient", "方便的", "kənˈviːniənt", "Convenient transportation.", "方便的交通。", 2, "gaokao"],
  ["convey", "传达", "kənˈveɪ", "Convey the message.", "传达信息。", 2, "gaokao"],
  ["convince", "说服", "kənˈvɪns", "Convince the audience.", "说服听众。", 2, "gaokao"],
  ["cooperate", "合作", "koʊˈɒpəreɪt", "Cooperate with team.", "与团队合作。", 2, "gaokao"],
  ["correspond", "对应；通信", "ˌkɒrəˈspɒnd", "Correspond with friends.", "和朋友通信。", 3, "gaokao"],
  ["creative", "有创意的", "kriˈeɪtɪv", "Creative thinking.", "创造性思维。", 2, "gaokao"],
  ["credit", "信用；学分", "ˈkredɪt", "Get credit.", "获得学分。", 2, "gaokao"],
  ["critical", "批评的；关键的", "ˈkrɪtɪkl", "Critical thinking.", "批判性思维。", 2, "gaokao"],
  ["cultivate", "培养", "ˈkʌltɪveɪt", "Cultivate good habits.", "培养好习惯。", 2, "gaokao"],
  ["curious", "好奇的", "ˈkjʊriəs", "Curious about everything.", "对一切好奇。", 2, "gaokao"],
  ["damage", "损坏", "ˈdæmɪdʒ", "Damage the environment.", "破坏环境。", 2, "gaokao"],
  ["debate", "辩论", "dɪˈbeɪt", "Debate the issue.", "辩论这个问题。", 2, "gaokao"],
  ["decade", "十年", "ˈdekeɪd", "Over the past decade.", "在过去十年。", 2, "gaokao"],
  ["decline", "下降；拒绝", "dɪˈklaɪn", "Decline the invitation.", "拒绝邀请。", 2, "gaokao"],
  ["decorate", "装饰", "ˈdekəreɪt", "Decorate the room.", "装饰房间。", 2, "gaokao"],
  ["decrease", "减少", "dɪˈkriːs", "Decrease pollution.", "减少污染。", 2, "gaokao"],
  ["defeat", "击败", "dɪˈfiːt", "Defeat the enemy.", "击败敌人。", 2, "gaokao"],
  ["defend", "防御", "dɪˈfend", "Defend your country.", "保卫国家。", 2, "gaokao"],
  ["define", "定义", "dɪˈfaɪn", "Define the term.", "定义这个术语。", 2, "gaokao"],
  ["deliver", "递送；发表", "dɪˈlɪvər", "Deliver a speech.", "发表演讲。", 2, "gaokao"],
  ["demand", "需求", "dɪˈmænd", "Supply and demand.", "供给和需求。", 2, "gaokao"],
  ["demonstrate", "展示；证明", "ˈdemənstreɪt", "Demonstrate the product.", "展示产品。", 3, "gaokao"],
  ["departure", "离开", "dɪˈpɑːrtʃər", "Departure time.", "出发时间。", 2, "gaokao"],
  ["depend", "依赖", "dɪˈpend", "Depend on yourself.", "依靠自己。", 2, "gaokao"],
  ["deposit", "存放；押金", "dɪˈpɒzɪt", "Deposit money.", "存钱。", 2, "gaokao"],
  ["depress", "使沮丧", "dɪˈpres", "Don't be depressed.", "别沮丧。", 2, "gaokao"],
  ["deserve", "值得", "dɪˈzɜːrv", "You deserve it.", "你值得拥有。", 2, "gaokao"],
  ["destination", "目的地", "ˌdestɪˈneɪʃn", "Final destination.", "最终目的地。", 2, "gaokao"],
  ["determine", "决定", "dɪˈtɜːrmɪn", "Determine the cause.", "确定原因。", 2, "gaokao"],
  ["device", "设备", "dɪˈvaɪs", "Electronic device.", "电子设备。", 2, "gaokao"],
  ["devote", "致力于", "dɪˈvoʊt", "Devote to study.", "专心学习。", 2, "gaokao"],
  ["dignity", "尊严", "ˈdɪɡnəti", "Human dignity.", "人的尊严。", 3, "gaokao"],
  ["dilemma", "困境", "dɪˈlemə", "In a dilemma.", "进退两难。", 3, "gaokao"],
  ["dimension", "方面；维度", "daɪˈmenʃn", "New dimension.", "新维度。", 3, "gaokao"],
  ["discipline", "纪律；学科", "ˈdɪsəplɪn", "Keep discipline.", "遵守纪律。", 2, "gaokao"],
  ["discount", "折扣", "ˈdɪskaʊnt", "Get a discount.", "打折。", 2, "gaokao"],
  ["discrimination", "歧视", "dɪˌskrɪmɪˈneɪʃn", "Racial discrimination.", "种族歧视。", 3, "gaokao"],
  ["disgust", "厌恶", "dɪsˈɡʌst", "Feel disgust.", "感到厌恶。", 2, "gaokao"],
  ["dismiss", "解散；解雇", "dɪsˈmɪs", "Dismiss the class.", "下课。", 2, "gaokao"],
  ["display", "展示", "dɪˈspleɪ", "Display the product.", "展示产品。", 2, "gaokao"],
  ["distinguish", "区分", "dɪˈstɪŋɡwɪʃ", "Distinguish right from wrong.", "明辨是非。", 3, "gaokao"],
  ["distribute", "分配", "dɪˈstrɪbjuːt", "Distribute resources.", "分配资源。", 3, "gaokao"],
  ["disturb", "打扰", "dɪˈstɜːrb", "Don't disturb.", "请勿打扰。", 2, "gaokao"],
  ["diverse", "多样的", "daɪˈvɜːrs", "Diverse culture.", "多样的文化。", 2, "gaokao"],
  ["domestic", "国内的", "dəˈmestɪk", "Domestic market.", "国内市场。", 2, "gaokao"],
  ["dominate", "主导", "ˈdɒmɪneɪt", "Dominate the game.", "主导比赛。", 3, "gaokao"],
  ["dramatic", "戏剧性的", "drəˈmætɪk", "Dramatic change.", "戏剧性的变化。", 2, "gaokao"],
  ["drought", "干旱", "draʊt", "Suffer from drought.", "遭受干旱。", 2, "gaokao"],
  ["durable", "耐用的", "ˈdʊrəbl", "Durable material.", "耐用材料。", 2, "gaokao"],
  ["dynamic", "动态的", "daɪˈnæmɪk", "Dynamic development.", "动态发展。", 3, "gaokao"],
  ["economy", "经济", "ɪˈkɒnəmi", "Market economy.", "市场经济。", 2, "gaokao"],
  ["educate", "教育", "ˈedʒukeɪt", "Educate children.", "教育孩子。", 2, "gaokao"],
  ["efficiency", "效率", "ɪˈfɪʃnsi", "Improve efficiency.", "提高效率。", 2, "gaokao"],
  ["eliminate", "消除", "ɪˈlɪmɪneɪt", "Eliminate poverty.", "消除贫困。", 3, "gaokao"],
  ["embarrass", "使尴尬", "ɪmˈbærəs", "Embarrass me.", "让我尴尬。", 2, "gaokao"],
  ["emerge", "出现", "iˈmɜːrdʒ", "New problems emerge.", "新问题出现。", 2, "gaokao"],
  ["emergency", "紧急情况", "iˈmɜːrdʒənsi", "Emergency exit.", "紧急出口。", 2, "gaokao"],
  ["emotion", "情感", "ɪˈmoʊʃn", "Control emotions.", "控制情绪。", 2, "gaokao"],
  ["emphasis", "强调", "ˈemfəsɪs", "Put emphasis on.", "强调。", 2, "gaokao"],
  ["employ", "雇用", "ɪmˈplɔɪ", "Employ workers.", "雇用工人。", 2, "gaokao"],
  ["enable", "使能够", "ɪˈneɪbl", "Enable progress.", "使进步成为可能。", 2, "gaokao"],
  ["encounter", "遇到", "ɪnˈkaʊntər", "Encounter difficulties.", "遇到困难。", 2, "gaokao"],
  ["encourage", "鼓励", "ɪnˈkɜːrɪdʒ", "Encourage each other.", "互相鼓励。", 2, "gaokao"],
  ["energy", "精力；能量", "ˈenərdʒi", "Full of energy.", "充满活力。", 2, "gaokao"],
  ["engage", "从事；吸引", "ɪnˈɡeɪdʒ", "Engage in conversation.", "参与对话。", 2, "gaokao"],
  ["enormous", "巨大的", "ɪˈnɔːrməs", "Enormous amount.", "巨大的数量。", 2, "gaokao"],
  ["ensure", "确保", "ɪnˈʃʊr", "Ensure safety.", "确保安全。", 2, "gaokao"],
  ["enterprise", "企业", "ˈentərpraɪz", "Business enterprise.", "商业企业。", 3, "gaokao"],
  ["enthusiasm", "热情", "ɪnˈθuːziæzəm", "Full of enthusiasm.", "充满热情。", 2, "gaokao"],
  ["environment", "环境", "ɪnˈvaɪrənmənt", "Protect the environment.", "保护环境。", 2, "gaokao"],
  ["equipment", "设备", "ɪˈkwɪpmənt", "Sports equipment.", "运动设备。", 2, "gaokao"],
  ["equivalent", "等价的", "ɪˈkwɪvələnt", "Equivalent to.", "相当于。", 3, "gaokao"],
  ["escape", "逃跑；逃避", "ɪˈskeɪp", "Escape from prison.", "越狱。", 2, "gaokao"],
  ["essential", "必要的", "ɪˈsenʃl", "Essential for life.", "生活必需。", 2, "gaokao"],
  ["establish", "建立", "ɪˈstæblɪʃ", "Establish a company.", "成立公司。", 2, "gaokao"],
  ["evaluate", "评价", "ɪˈvæljueɪt", "Evaluate the result.", "评价结果。", 3, "gaokao"],
  ["evidence", "证据", "ˈevɪdəns", "Find evidence.", "寻找证据。", 2, "gaokao"],
  ["evolve", "进化；发展", "iˈvɒlv", "Evolve over time.", "随着时间进化。", 3, "gaokao"],
  ["examine", "检查；考试", "ɪɡˈzæmɪn", "Examine the patient.", "检查病人。", 2, "gaokao"],
  ["excellent", "优秀的", "ˈeksələnt", "Excellent student.", "优秀的学生。", 2, "gaokao"],
  ["exchange", "交换", "ɪksˈtʃeɪndʒ", "Exchange ideas.", "交换意见。", 2, "gaokao"],
  ["exhibit", "展览", "ɪɡˈzɪbɪt", "Exhibit paintings.", "展览画作。", 2, "gaokao"],
  ["expand", "扩展", "ɪkˈspænd", "Expand business.", "扩展业务。", 2, "gaokao"],
  ["expense", "花费", "ɪkˈspens", "Living expenses.", "生活费用。", 2, "gaokao"],
  ["experiment", "实验", "ɪkˈsperɪmənt", "Do an experiment.", "做实验。", 2, "gaokao"],
  ["expert", "专家", "ˈekspɜːrt", "Expert opinion.", "专家意见。", 2, "gaokao"],
  ["exploit", "开发；利用", "ɪkˈsplɔɪt", "Exploit resources.", "开发资源。", 3, "gaokao"],
  ["explore", "探索", "ɪkˈsplɔːr", "Explore the world.", "探索世界。", 2, "gaokao"],
  ["export", "出口", "ˈekspɔːrt", "Export goods.", "出口商品。", 2, "gaokao"],
  ["expose", "暴露", "ɪkˈspoʊz", "Expose to the sun.", "暴露在阳光下。", 2, "gaokao"],
  ["extend", "延伸", "ɪkˈstend", "Extend the deadline.", "延长截止日期。", 2, "gaokao"],
  ["extraordinary", "非凡的", "ɪkˈstrɔːrdəneri", "Extraordinary achievement.", "非凡的成就。", 3, "gaokao"],
  ["extreme", "极端的", "ɪkˈstriːm", "Extreme weather.", "极端天气。", 2, "gaokao"],
  ["facility", "设施", "fəˈsɪləti", "Public facilities.", "公共设施。", 2, "gaokao"],
  ["factor", "因素", "ˈfæktər", "Key factor.", "关键因素。", 2, "gaokao"],
  ["familiar", "熟悉的", "fəˈmɪliər", "Familiar with.", "熟悉。", 2, "gaokao"],
  ["fascinate", "使着迷", "ˈfæsɪneɪt", "Fascinate the audience.", "让观众着迷。", 2, "gaokao"],
  ["fatal", "致命的", "ˈfeɪtl", "Fatal mistake.", "致命的错误。", 2, "gaokao"],
  ["fatigue", "疲劳", "fəˈtiːɡ", "Feel fatigue.", "感到疲劳。", 2, "gaokao"],
  ["feature", "特征", "ˈfiːtʃər", "Main feature.", "主要特征。", 2, "gaokao"],
  ["finance", "金融；财务", "ˈfaɪnæns", "Finance department.", "财务部门。", 2, "gaokao"],
  ["flexible", "灵活的", "ˈfleksəbl", "Flexible schedule.", "灵活的时间表。", 2, "gaokao"],
  ["flourish", "繁荣", "ˈflɜːrɪʃ", "Business flourishes.", "生意兴隆。", 3, "gaokao"],
  ["forbid", "禁止", "fərˈbɪd", "Smoking forbidden.", "禁止吸烟。", 2, "gaokao"],
  ["forecast", "预测", "ˈfɔːrkæst", "Weather forecast.", "天气预报。", 2, "gaokao"],
  ["fortune", "财富；运气", "ˈfɔːrtʃən", "Make a fortune.", "发财。", 2, "gaokao"],
  ["foundation", "基础", "faʊnˈdeɪʃn", "Solid foundation.", "坚实的基础。", 2, "gaokao"],
  ["frequent", "频繁的", "ˈfriːkwənt", "Frequent visits.", "频繁的访问。", 2, "gaokao"],
  ["frontier", "前沿；边界", "frʌnˈtɪr", "Technology frontier.", "技术前沿。", 3, "gaokao"],
  ["frustrate", "使沮丧", "ˈfrʌstreɪt", "Feel frustrated.", "感到沮丧。", 2, "gaokao"],
  ["function", "功能", "ˈfʌŋkʃn", "Basic function.", "基本功能。", 2, "gaokao"],
  ["fundamental", "基本的", "ˌfʌndəˈmentl", "Fundamental rights.", "基本权利。", 3, "gaokao"],
  ["generate", "产生", "ˈdʒenəreɪt", "Generate electricity.", "发电。", 2, "gaokao"],
  ["generous", "慷慨的", "ˈdʒenərəs", "Generous donation.", "慷慨的捐赠。", 2, "gaokao"],
  ["genius", "天才", "ˈdʒiːniəs", "Mathematical genius.", "数学天才。", 2, "gaokao"],
  ["global", "全球的", "ˈɡloʊbl", "Global warming.", "全球变暖。", 2, "gaokao"],
  ["gradual", "逐渐的", "ˈɡrædʒuəl", "Gradual improvement.", "逐步改进。", 2, "gaokao"],
  ["guarantee", "保证", "ˌɡærənˈtiː", "Guarantee quality.", "保证质量。", 2, "gaokao"],
  ["harmony", "和谐", "ˈhɑːrməni", "Live in harmony.", "和谐相处。", 2, "gaokao"],
  ["hesitate", "犹豫", "ˈhezɪteɪt", "Don't hesitate.", "别犹豫。", 2, "gaokao"],
  ["highlight", "强调；亮点", "ˈhaɪlaɪt", "Highlight the point.", "强调重点。", 2, "gaokao"],
  ["ignorant", "无知的", "ˈɪɡnərənt", "Don't be ignorant.", "别无知。", 2, "gaokao"],
  ["illustrate", "说明", "ˈɪləstreɪt", "Illustrate the point.", "说明这一点。", 3, "gaokao"],
  ["imagination", "想象力", "ɪˌmædʒɪˈneɪʃn", "Use your imagination.", "发挥你的想象力。", 2, "gaokao"],
  ["immediate", "立即的", "ɪˈmiːdiət", "Immediate action.", "立即行动。", 2, "gaokao"],
  ["immigrant", "移民", "ˈɪmɪɡrənt", "Immigrant worker.", "移民工人。", 2, "gaokao"],
  ["impact", "影响", "ˈɪmpækt", "Have impact on.", "对…有影响。", 2, "gaokao"],
  ["implement", "实施", "ˈɪmplɪment", "Implement the plan.", "实施计划。", 3, "gaokao"],
  ["imply", "暗示", "ɪmˈplaɪ", "What does it imply?", "它暗示什么？", 2, "gaokao"],
  ["impose", "强加", "ɪmˈpoʊz", "Impose a tax.", "征税。", 3, "gaokao"],
  ["impress", "留下印象", "ɪmˈpres", "Impress the teacher.", "给老师留下好印象。", 2, "gaokao"],
  ["income", "收入", "ˈɪnkʌm", "Monthly income.", "月收入。", 2, "gaokao"],
  ["independent", "独立的", "ˌɪndɪˈpendənt", "Independent thinking.", "独立思考。", 2, "gaokao"],
  ["indicate", "表明", "ˈɪndɪkeɪt", "Indicate the direction.", "指示方向。", 2, "gaokao"],
  ["individual", "个人的；个体", "ˌɪndɪˈvɪdʒuəl", "Individual rights.", "个人权利。", 2, "gaokao"],
  ["industry", "工业；行业", "ˈɪndəstri", "Manufacturing industry.", "制造业。", 2, "gaokao"],
  ["influence", "影响", "ˈɪnfluəns", "Positive influence.", "积极影响。", 2, "gaokao"],
  ["inform", "通知", "ɪnˈfɔːrm", "Inform the public.", "通知公众。", 2, "gaokao"],
  ["initiative", "倡议；主动性", "ɪˈnɪʃətɪv", "Take initiative.", "采取主动。", 3, "gaokao"],
  ["innovation", "创新", "ˌɪnəˈveɪʃn", "Technological innovation.", "技术创新。", 2, "gaokao"],
  ["inspire", "激励", "ɪnˈspaɪər", "Inspire others.", "激励他人。", 2, "gaokao"],
  ["institute", "学院；机构", "ˈɪnstɪtuːt", "Research institute.", "研究所。", 2, "gaokao"],
  ["instrument", "工具；乐器", "ˈɪnstrəmənt", "Musical instrument.", "乐器。", 2, "gaokao"],
  ["insurance", "保险", "ɪnˈʃʊrəns", "Health insurance.", "健康保险。", 2, "gaokao"],
  ["intellectual", "智力的", "ˌɪntəˈlektʃuəl", "Intellectual property.", "知识产权。", 3, "gaokao"],
  ["intelligence", "智力；情报", "ɪnˈtelɪdʒəns", "Artificial intelligence.", "人工智能。", 2, "gaokao"],
  ["intense", "强烈的", "ɪnˈtens", "Intense competition.", "激烈的竞争。", 2, "gaokao"],
  ["interact", "互动", "ˌɪntərˈækt", "Interact with others.", "与他人互动。", 2, "gaokao"],
  ["interpret", "解释；口译", "ɪnˈtɜːrprɪt", "Interpret the meaning.", "解释含义。", 3, "gaokao"],
  ["interrupt", "打断", "ˌɪntəˈrʌpt", "Don't interrupt.", "别打断。", 2, "gaokao"],
  ["investigate", "调查", "ɪnˈvestɪɡeɪt", "Investigate the case.", "调查案件。", 2, "gaokao"],
  ["investment", "投资", "ɪnˈvestmənt", "Make investment.", "进行投资。", 2, "gaokao"],
  ["involve", "涉及", "ɪnˈvɒlv", "Involve everyone.", "让每个人参与。", 2, "gaokao"],
  ["isolate", "隔离", "ˈaɪsəleɪt", "Isolate the patient.", "隔离病人。", 2, "gaokao"],
  ["issue", "问题；发行", "ˈɪʃuː", "Current issue.", "当前问题。", 2, "gaokao"],
  ["journalist", "记者", "ˈdʒɜːrnəlɪst", "Work as a journalist.", "做记者。", 2, "gaokao"],
  ["justice", "正义", "ˈdʒʌstɪs", "Social justice.", "社会正义。", 2, "gaokao"],
  ["justify", "证明…正确", "ˈdʒʌstɪfaɪ", "Justify the decision.", "证明决定正确。", 3, "gaokao"],
  ["knowledge", "知识", "ˈnɒlɪdʒ", "Knowledge is power.", "知识就是力量。", 2, "gaokao"],
  ["labor", "劳动", "ˈleɪbər", "Labor force.", "劳动力。", 2, "gaokao"],
  ["landscape", "风景", "ˈlændskeɪp", "Beautiful landscape.", "美丽的风景。", 2, "gaokao"],
  ["launch", "发射；启动", "lɔːntʃ", "Launch a product.", "推出产品。", 2, "gaokao"],
  ["leadership", "领导力", "ˈliːdərʃɪp", "Strong leadership.", "强大的领导力。", 2, "gaokao"],
  ["legal", "合法的", "ˈliːɡl", "Legal action.", "法律行动。", 2, "gaokao"],
  ["liberal", "自由的", "ˈlɪbərəl", "Liberal arts.", "文科。", 3, "gaokao"],
  ["literacy", "读写能力", "ˈlɪtərəsi", "Improve literacy.", "提高读写能力。", 3, "gaokao"],
  ["literature", "文学", "ˈlɪtrətʃər", "Chinese literature.", "中国文学。", 2, "gaokao"],
  ["local", "当地的", "ˈloʊkl", "Local people.", "当地人。", 2, "gaokao"],
  ["locate", "位于", "ˈloʊkeɪt", "Located in Beijing.", "位于北京。", 2, "gaokao"],
  ["logical", "逻辑的", "ˈlɒdʒɪkl", "Logical thinking.", "逻辑思维。", 2, "gaokao"],
  ["maintain", "维持", "meɪnˈteɪn", "Maintain friendship.", "维持友谊。", 2, "gaokao"],
  ["major", "主要的；专业", "ˈmeɪdʒər", "Major problem.", "主要问题。", 2, "gaokao"],
  ["manage", "管理", "ˈmænɪdʒ", "Manage the company.", "管理公司。", 2, "gaokao"],
  ["manufacture", "制造", "ˌmænjuˈfæktʃər", "Manufacture products.", "制造产品。", 3, "gaokao"],
  ["massive", "大规模的", "ˈmæsɪv", "Massive change.", "巨大的变化。", 2, "gaokao"],
  ["material", "材料", "məˈtɪriəl", "Building materials.", "建筑材料。", 2, "gaokao"],
  ["mature", "成熟的", "məˈtʃʊr", "Mature person.", "成熟的人。", 2, "gaokao"],
  ["maximum", "最大的", "ˈmæksɪməm", "Maximum speed.", "最快速度。", 2, "gaokao"],
  ["measure", "测量；措施", "ˈmeʒər", "Take measures.", "采取措施。", 2, "gaokao"],
  ["medium", "媒介；中等的", "ˈmiːdiəm", "Medium size.", "中等尺寸。", 2, "gaokao"],
  ["mental", "精神的", "ˈmentl", "Mental health.", "心理健康。", 2, "gaokao"],
  ["mention", "提及", "ˈmenʃn", "Don't mention it.", "不客气。", 2, "gaokao"],
  ["merchant", "商人", "ˈmɜːrtʃənt", "Local merchant.", "当地商人。", 2, "gaokao"],
  ["minority", "少数", "maɪˈnɒrəti", "Minority group.", "少数民族。", 2, "gaokao"],
  ["mission", "使命", "ˈmɪʃn", "Complete the mission.", "完成任务。", 2, "gaokao"],
  ["modify", "修改", "ˈmɒdɪfaɪ", "Modify the plan.", "修改计划。", 2, "gaokao"],
  ["monitor", "监视；监控", "ˈmɒnɪtər", "Monitor the situation.", "监控局势。", 2, "gaokao"],
  ["moral", "道德的", "ˈmɒrəl", "Moral values.", "道德价值观。", 2, "gaokao"],
  ["motivate", "激励", "ˈmoʊtɪveɪt", "Motivate students.", "激励学生。", 2, "gaokao"],
  ["mutual", "相互的", "ˈmjuːtʃuəl", "Mutual understanding.", "相互理解。", 2, "gaokao"],
  ["negative", "消极的；阴性的", "ˈneɡətɪv", "Negative effect.", "负面影响。", 2, "gaokao"],
  ["negotiate", "谈判", "nɪˈɡoʊʃieɪt", "Negotiate a deal.", "谈判协议。", 3, "gaokao"],
  ["network", "网络", "ˈnetwɜːrk", "Social network.", "社交网络。", 2, "gaokao"],
  ["neutral", "中立的", "ˈnuːtrəl", "Neutral position.", "中立立场。", 2, "gaokao"],
  ["nonetheless", "尽管如此", "ˌnʌnðəˈles", "Nonetheless, it's true.", "尽管如此，这是真的。", 3, "gaokao"],
  ["normal", "正常的", "ˈnɔːrml", "Normal life.", "正常生活。", 2, "gaokao"],
  ["numerous", "许多的", "ˈnuːmərəs", "Numerous reasons.", "许多原因。", 2, "gaokao"],
  ["obtain", "获得", "əbˈteɪn", "Obtain knowledge.", "获得知识。", 2, "gaokao"],
  ["obvious", "明显的", "ˈɒbviəs", "Obvious reason.", "明显的原因。", 2, "gaokao"],
  ["occupy", "占据", "ˈɒkjupaɪ", "Occupy the city.", "占领城市。", 2, "gaokao"],
  ["offend", "冒犯", "əˈfend", "Offend someone.", "冒犯某人。", 2, "gaokao"],
  ["operate", "操作；经营", "ˈɒpəreɪt", "Operate the machine.", "操作机器。", 2, "gaokao"],
  ["oppose", "反对", "əˈpoʊz", "Oppose the plan.", "反对这个计划。", 2, "gaokao"],
  ["optional", "可选的", "ˈɒpʃənl", "Optional course.", "选修课。", 2, "gaokao"],
  ["organize", "组织", "ˈɔːrɡənaɪz", "Organize the event.", "组织活动。", 2, "gaokao"],
  ["original", "原始的", "əˈrɪdʒənl", "Original plan.", "最初的计划。", 2, "gaokao"],
  ["overcome", "克服", "ˌoʊvərˈkʌm", "Overcome difficulties.", "克服困难。", 2, "gaokao"],
  ["overlook", "忽视", "ˌoʊvərˈlʊk", "Overlook the details.", "忽视细节。", 2, "gaokao"],
  ["participate", "参与", "pɑːrˈtɪsɪpeɪt", "Participate in class.", "参与课堂。", 2, "gaokao"],
  ["particular", "特别的", "pərˈtɪkjələr", "Particular case.", "特殊情况。", 2, "gaokao"],
  ["passion", "热情", "ˈpæʃn", "Passion for life.", "对生活的热情。", 2, "gaokao"],
  ["patience", "耐心", "ˈpeɪʃns", "Have patience.", "要有耐心。", 2, "gaokao"],
  ["pattern", "模式；图案", "ˈpætərn", "Behavior pattern.", "行为模式。", 2, "gaokao"],
  ["perceive", "感知", "pərˈsiːv", "Perceive the world.", "感知世界。", 3, "gaokao"],
  ["perform", "表现；表演", "pərˈfɔːrm", "Perform on stage.", "在舞台上表演。", 2, "gaokao"],
  ["permanent", "永久的", "ˈpɜːrmənənt", "Permanent address.", "永久地址。", 2, "gaokao"],
  ["permit", "允许", "pərˈmɪt", "Permit entry.", "允许进入。", 2, "gaokao"],
  ["persist", "坚持", "pərˈsɪst", "Persist in learning.", "坚持学习。", 2, "gaokao"],
  ["personality", "个性", "ˌpɜːrsəˈnæləti", "Strong personality.", "坚强的个性。", 2, "gaokao"],
  ["perspective", "观点", "pərˈspektɪv", "From my perspective.", "从我的角度看。", 2, "gaokao"],
  ["phenomenon", "现象", "fəˈnɒmɪnən", "Social phenomenon.", "社会现象。", 3, "gaokao"],
  ["philosophy", "哲学", "fəˈlɒsəfi", "Life philosophy.", "人生哲学。", 3, "gaokao"],
  ["physical", "身体的；物理的", "ˈfɪzɪkl", "Physical exercise.", "体育锻炼。", 2, "gaokao"],
  ["pollution", "污染", "pəˈluːʃn", "Air pollution.", "空气污染。", 2, "gaokao"],
  ["population", "人口", "ˌpɒpjuˈleɪʃn", "Large population.", "人口众多。", 2, "gaokao"],
  ["portion", "部分", "ˈpɔːrʃn", "Main portion.", "主要部分。", 2, "gaokao"],
  ["possess", "拥有", "pəˈzes", "Possess great talent.", "拥有巨大天赋。", 2, "gaokao"],
  ["potential", "潜力", "pəˈtenʃl", "Full potential.", "全部潜力。", 2, "gaokao"],
  ["poverty", "贫穷", "ˈpɒvərti", "Poverty of ideas.", "思想贫乏。", 2, "gaokao"],
  ["practical", "实用的", "ˈpræktɪkl", "Practical skills.", "实用技能。", 2, "gaokao"],
  ["precious", "珍贵的", "ˈpreʃəs", "Precious time.", "宝贵的时间。", 2, "gaokao"],
  ["predict", "预测", "prɪˈdɪkt", "Predict the future.", "预测未来。", 2, "gaokao"],
  ["prefer", "更喜欢", "prɪˈfɜːr", "I prefer tea.", "我更喜欢茶。", 2, "gaokao"],
  ["preserve", "保护；保存", "prɪˈzɜːrv", "Preserve the environment.", "保护环境。", 2, "gaokao"],
  ["pressure", "压力", "ˈpreʃər", "Under pressure.", "在压力下。", 2, "gaokao"],
  ["previous", "之前的", "ˈpriːviəs", "Previous experience.", "之前的经历。", 2, "gaokao"],
  ["principle", "原则", "ˈprɪnsəpl", "Moral principle.", "道德原则。", 2, "gaokao"],
  ["privilege", "特权", "ˈprɪvəlɪdʒ", "Great privilege.", "极大的荣幸。", 3, "gaokao"],
  ["procedure", "程序", "prəˈsiːdʒər", "Standard procedure.", "标准程序。", 2, "gaokao"],
  ["profession", "职业", "prəˈfeʃn", "Teaching profession.", "教师职业。", 2, "gaokao"],
  ["profit", "利润", "ˈprɒfɪt", "Make profit.", "获利。", 2, "gaokao"],
  ["progress", "进步", "ˈprɑːɡres", "Make progress.", "取得进步。", 2, "gaokao"],
  ["promote", "促进；提升", "prəˈmoʊt", "Promote health.", "促进健康。", 2, "gaokao"],
  ["prospect", "前景", "ˈprɑːspekt", "Bright prospect.", "光明的前景。", 2, "gaokao"],
  ["protest", "抗议", "ˈproʊtest", "Protest against.", "抗议。", 2, "gaokao"],
  ["provide", "提供", "prəˈvaɪd", "Provide service.", "提供服务。", 2, "gaokao"],
  ["psychology", "心理学", "saɪˈkɒlədʒi", "Educational psychology.", "教育心理学。", 3, "gaokao"],
  ["publish", "出版", "ˈpʌblɪʃ", "Publish a book.", "出版一本书。", 2, "gaokao"],
  ["purchase", "购买", "ˈpɜːrtʃəs", "Purchase goods.", "购买商品。", 2, "gaokao"],
  ["pursue", "追求", "pərˈsuː", "Pursue your dream.", "追求梦想。", 2, "gaokao"],
  ["qualification", "资格", "ˌkwɒlɪfɪˈkeɪʃn", "Get qualified.", "获得资格。", 2, "gaokao"],
  ["quantity", "数量", "ˈkwɒntəti", "Large quantity.", "大量。", 2, "gaokao"],
  ["range", "范围", "reɪndʒ", "Price range.", "价格范围。", 2, "gaokao"],
  ["rare", "稀有的", "rer", "Rare species.", "稀有物种。", 2, "gaokao"],
  ["rational", "理性的", "ˈræʃnəl", "Rational decision.", "理性的决定。", 3, "gaokao"],
  ["reality", "现实", "riˈæləti", "Face reality.", "面对现实。", 2, "gaokao"],
  ["reasonable", "合理的", "ˈriːznəbl", "Reasonable price.", "合理价格。", 2, "gaokao"],
  ["recognize", "认出；承认", "ˈrekəɡnaɪz", "Recognize the importance.", "认识到重要性。", 2, "gaokao"],
  ["recommend", "推荐", "ˌrekəˈmend", "Recommend a book.", "推荐一本书。", 2, "gaokao"],
  ["recover", "恢复", "rɪˈkʌvər", "Recover from illness.", "从疾病中恢复。", 2, "gaokao"],
  ["reduce", "减少", "rɪˈduːs", "Reduce pollution.", "减少污染。", 2, "gaokao"],
  ["refer", "参考；提及", "rɪˈfɜːr", "Refer to the note.", "参考笔记。", 2, "gaokao"],
  ["reflect", "反映；反思", "rɪˈflekt", "Reflect on your actions.", "反思你的行为。", 2, "gaokao"],
  ["reform", "改革", "rɪˈfɔːrm", "Education reform.", "教育改革。", 2, "gaokao"],
  ["regard", "认为；关注", "rɪˈɡɑːrd", "Regard as important.", "认为重要。", 2, "gaokao"],
  ["register", "注册", "ˈredʒɪstər", "Register for class.", "注册课程。", 2, "gaokao"],
  ["regulate", "调节", "ˈreɡjuleɪt", "Regulate temperature.", "调节温度。", 3, "gaokao"],
  ["reject", "拒绝", "rɪˈdʒekt", "Reject the offer.", "拒绝提议。", 2, "gaokao"],
  ["relate", "关联", "rɪˈleɪt", "Relate to real life.", "与现实生活相关。", 2, "gaokao"],
  ["release", "释放；发布", "rɪˈliːs", "Release the news.", "发布消息。", 2, "gaokao"],
  ["relevant", "相关的", "ˈreləvənt", "Relevant information.", "相关信息。", 2, "gaokao"],
  ["relief", "缓解；解脱", "rɪˈliːf", "Feel relief.", "感到解脱。", 2, "gaokao"],
  ["religion", "宗教", "rɪˈlɪdʒən", "Freedom of religion.", "宗教自由。", 2, "gaokao"],
  ["reluctant", "不情愿的", "rɪˈlʌktənt", "Reluctant to go.", "不愿去。", 2, "gaokao"],
  ["rely", "依赖", "rɪˈlaɪ", "Rely on yourself.", "依靠自己。", 2, "gaokao"],
  ["remain", "保持；留下", "rɪˈmeɪn", "Remain calm.", "保持冷静。", 2, "gaokao"],
  ["remarkable", "显著的", "rɪˈmɑːrkəbl", "Remarkable achievement.", "显著成就。", 2, "gaokao"],
  ["remedy", "补救", "ˈremədi", "Remedy the situation.", "补救局势。", 3, "gaokao"],
  ["remote", "遥远的", "rɪˈmoʊt", "Remote area.", "偏远地区。", 2, "gaokao"],
  ["remove", "移除", "rɪˈmuːv", "Remove the obstacle.", "移除障碍。", 2, "gaokao"],
  ["replace", "取代", "rɪˈpleɪs", "Replace the old one.", "替换旧的。", 2, "gaokao"],
  ["represent", "代表", "ˌreprɪˈzent", "Represent our school.", "代表我们学校。", 2, "gaokao"],
  ["reputation", "声誉", "ˌrepjuˈteɪʃn", "Good reputation.", "好声誉。", 2, "gaokao"],
  ["request", "请求", "rɪˈkwest", "Request help.", "请求帮助。", 2, "gaokao"],
  ["require", "要求", "rɪˈkwaɪər", "Require attention.", "需要关注。", 2, "gaokao"],
  ["research", "研究", "rɪˈsɜːrtʃ", "Do research.", "做研究。", 2, "gaokao"],
  ["reserve", "保留；预订", "rɪˈzɜːrv", "Reserve a seat.", "预订座位。", 2, "gaokao"],
  ["resign", "辞职", "rɪˈzaɪn", "Resign from job.", "辞职。", 2, "gaokao"],
  ["resist", "抵抗", "rɪˈzɪst", "Resist temptation.", "抵制诱惑。", 2, "gaokao"],
  ["resolve", "解决", "rɪˈzɒlv", "Resolve the problem.", "解决问题。", 2, "gaokao"],
  ["resource", "资源", "rɪˈsɔːrs", "Natural resources.", "自然资源。", 2, "gaokao"],
  ["respond", "回应", "rɪˈspɒnd", "Respond quickly.", "快速回应。", 2, "gaokao"],
  ["responsible", "负责的", "rɪˈspɒnsəbl", "Be responsible.", "负责任。", 2, "gaokao"],
  ["restore", "恢复", "rɪˈstɔːr", "Restore the building.", "修复建筑。", 2, "gaokao"],
  ["restrict", "限制", "rɪˈstrɪkt", "Restrict access.", "限制访问。", 2, "gaokao"],
  ["reveal", "揭示", "rɪˈviːl", "Reveal the truth.", "揭示真相。", 2, "gaokao"],
  ["revolution", "革命", "ˌrevəˈluːʃn", "Industrial revolution.", "工业革命。", 2, "gaokao"],
  ["risk", "风险", "rɪsk", "Take a risk.", "冒险。", 2, "gaokao"],
  ["routine", "常规", "ruːˈtiːn", "Daily routine.", "日常生活。", 2, "gaokao"],
  ["sacrifice", "牺牲", "ˈsækrɪfaɪs", "Make sacrifices.", "做出牺牲。", 2, "gaokao"],
  ["satisfaction", "满意", "ˌsætɪsˈfækʃn", "Customer satisfaction.", "客户满意度。", 2, "gaokao"],
  ["schedule", "时间表", "ˈskedʒuːl", "Busy schedule.", "繁忙的日程。", 2, "gaokao"],
  ["scheme", "计划；方案", "skiːm", "Proposed scheme.", "提议方案。", 2, "gaokao"],
  ["security", "安全", "sɪˈkjʊrəti", "National security.", "国家安全。", 2, "gaokao"],
  ["senior", "高级的", "ˈsiːniər", "Senior citizen.", "老年人。", 2, "gaokao"],
  ["sensitive", "敏感的", "ˈsensətɪv", "Sensitive topic.", "敏感话题。", 2, "gaokao"],
  ["separate", "分开", "ˈsepəreɪt", "Separate the items.", "分开物品。", 2, "gaokao"],
  ["serious", "严重的；认真的", "ˈsɪriəs", "Serious problem.", "严重的问题。", 2, "gaokao"],
  ["settle", "解决；定居", "ˈsetl", "Settle the dispute.", "解决争端。", 2, "gaokao"],
  ["severe", "严重的", "sɪˈvɪr", "Severe weather.", "恶劣天气。", 2, "gaokao"],
  ["shelter", "庇护所", "ˈʃeltər", "Take shelter.", "躲避。", 2, "gaokao"],
  ["signal", "信号", "ˈsɪɡnəl", "Traffic signal.", "交通信号。", 2, "gaokao"],
  ["significant", "重要的", "sɪɡˈnɪfɪkənt", "Significant change.", "重大变化。", 2, "gaokao"],
  ["similar", "相似的", "ˈsɪmələr", "Similar to mine.", "和我的相似。", 2, "gaokao"],
  ["sincere", "真诚的", "sɪnˈsɪr", "Sincere apology.", "真诚的道歉。", 2, "gaokao"],
  ["situation", "情况", "ˌsɪtʃuˈeɪʃn", "Current situation.", "当前状况。", 2, "gaokao"],
  ["society", "社会", "səˈsaɪəti", "Modern society.", "现代社会。", 2, "gaokao"],
  ["solution", "解决方案", "səˈluːʃn", "Find a solution.", "找到解决方案。", 2, "gaokao"],
  ["somewhat", "有点", "ˈsʌmwʌt", "Somewhat difficult.", "有点难。", 2, "gaokao"],
  ["source", "来源", "sɔːrs", "Source of energy.", "能源。", 2, "gaokao"],
  ["specific", "具体的", "spəˈsɪfɪk", "Specific details.", "具体细节。", 2, "gaokao"],
  ["stable", "稳定的", "ˈsteɪbl", "Stable economy.", "稳定的经济。", 2, "gaokao"],
  ["standard", "标准", "ˈstændərd", "High standard.", "高标准。", 2, "gaokao"],
  ["status", "地位；状态", "ˈsteɪtəs", "Social status.", "社会地位。", 2, "gaokao"],
  ["strategy", "策略", "ˈstrætədʒi", "Learning strategy.", "学习策略。", 2, "gaokao"],
  ["strength", "力量；优势", "streŋθ", "Inner strength.", "内心力量。", 2, "gaokao"],
  ["structure", "结构", "ˈstrʌktʃər", "Sentence structure.", "句子结构。", 2, "gaokao"],
  ["struggle", "奋斗；挣扎", "ˈstrʌɡl", "Struggle for success.", "为成功而奋斗。", 2, "gaokao"],
  ["substance", "物质", "ˈsʌbstəns", "Chemical substance.", "化学物质。", 2, "gaokao"],
  ["substitute", "替代", "ˈsʌbstɪtuːt", "Substitute for sugar.", "糖的替代品。", 3, "gaokao"],
  ["succeed", "成功", "səkˈsiːd", "Succeed in life.", "在生活中成功。", 2, "gaokao"],
  ["sufficient", "充足的", "səˈfɪʃnt", "Sufficient evidence.", "充足的证据。", 2, "gaokao"],
  ["suggest", "建议", "səˈdʒest", "Suggest a plan.", "建议一个计划。", 2, "gaokao"],
  ["summary", "总结", "ˈsʌməri", "Give a summary.", "做个总结。", 2, "gaokao"],
  ["supply", "供应", "səˈplaɪ", "Supply and demand.", "供求关系。", 2, "gaokao"],
  ["support", "支持", "səˈpɔːrt", "Support your family.", "养家。", 2, "gaokao"],
  ["suppose", "假设", "səˈpoʊz", "Suppose it's true.", "假设是真的。", 2, "gaokao"],
  ["surface", "表面", "ˈsɜːrfɪs", "On the surface.", "表面上。", 2, "gaokao"],
  ["survey", "调查", "ˈsɜːrveɪ", "Conduct a survey.", "进行调查。", 2, "gaokao"],
  ["survive", "生存", "sərˈvaɪv", "Survive the accident.", "在事故中幸存。", 2, "gaokao"],
  ["suspect", "怀疑", "səˈspekt", "Suspect the truth.", "怀疑真相。", 2, "gaokao"],
  ["suspend", "暂停", "səˈspend", "Suspend the activity.", "暂停活动。", 3, "gaokao"],
  ["sustain", "维持", "səˈsteɪn", "Sustain development.", "维持发展。", 3, "gaokao"],
  ["symbol", "象征", "ˈsɪmbl", "Symbol of peace.", "和平的象征。", 2, "gaokao"],
  ["sympathy", "同情", "ˈsɪmpəθi", "Show sympathy.", "表示同情。", 2, "gaokao"],
  ["target", "目标", "ˈtɑːrɡɪt", "Target audience.", "目标受众。", 2, "gaokao"],
  ["technique", "技术；技巧", "tekˈniːk", "Learning technique.", "学习技巧。", 2, "gaokao"],
  ["technology", "技术", "tekˈnɒlədʒi", "Information technology.", "信息技术。", 2, "gaokao"],
  ["temporary", "暂时的", "ˈtempəreri", "Temporary solution.", "临时方案。", 2, "gaokao"],
  ["tendency", "趋势", "ˈtendənsi", "Growing tendency.", "增长趋势。", 2, "gaokao"],
  ["tension", "紧张", "ˈtenʃn", "Ease tension.", "缓解紧张。", 2, "gaokao"],
  ["terminal", "终端的", "ˈtɜːrmɪnl", "Terminal station.", "终点站。", 2, "gaokao"],
  ["territory", "领土", "ˈterɪtɔːri", "National territory.", "国家领土。", 2, "gaokao"],
  ["thorough", "彻底的", "ˈθɜːroʊ", "Thorough examination.", "彻底检查。", 2, "gaokao"],
  ["threaten", "威胁", "ˈθretn", "Threaten safety.", "威胁安全。", 2, "gaokao"],
  ["tolerance", "容忍", "ˈtɒlərəns", "Show tolerance.", "表示宽容。", 3, "gaokao"],
  ["tough", "坚强的；艰难的", "tʌf", "Tough decision.", "艰难的决定。", 2, "gaokao"],
  ["tradition", "传统", "trəˈdɪʃn", "Cultural tradition.", "文化传统。", 2, "gaokao"],
  ["transform", "转变", "trænsˈfɔːrm", "Transform education.", "改革教育。", 2, "gaokao"],
  ["transportation", "交通", "ˌtrænspɔːrˈteɪʃn", "Public transportation.", "公共交通。", 2, "gaokao"],
  ["tremendous", "巨大的", "trəˈmendəs", "Tremendous progress.", "巨大的进步。", 2, "gaokao"],
  ["trend", "趋势", "trend", "Fashion trend.", "时尚趋势。", 2, "gaokao"],
  ["typical", "典型的", "ˈtɪpɪkl", "Typical example.", "典型的例子。", 2, "gaokao"],
  ["ultimate", "最终的", "ˈʌltɪmət", "Ultimate goal.", "最终目标。", 2, "gaokao"],
  ["universe", "宇宙", "ˈjuːnɪvɜːrs", "Explore the universe.", "探索宇宙。", 2, "gaokao"],
  ["urban", "城市的", "ˈɜːrbən", "Urban area.", "市区。", 2, "gaokao"],
  ["urge", "催促；强烈要求", "ɜːrdʒ", "Urge action.", "敦促采取行动。", 2, "gaokao"],
  ["vanish", "消失", "ˈvænɪʃ", "Vanish into thin air.", "消失得无影无踪。", 2, "gaokao"],
  ["variety", "多样性", "vəˈraɪəti", "Variety of options.", "多种选择。", 2, "gaokao"],
  ["version", "版本", "ˈvɜːrʒn", "Latest version.", "最新版本。", 2, "gaokao"],
  ["victim", "受害者", "ˈvɪktɪm", "Victim of crime.", "犯罪受害者。", 2, "gaokao"],
  ["violence", "暴力", "ˈvaɪələns", "Domestic violence.", "家庭暴力。", 2, "gaokao"],
  ["virtual", "虚拟的", "ˈvɜːrtʃuəl", "Virtual reality.", "虚拟现实。", 2, "gaokao"],
  ["visible", "可见的", "ˈvɪzəbl", "Visible progress.", "可见的进步。", 2, "gaokao"],
  ["vision", "视野；愿景", "ˈvɪʒn", "Broad vision.", "广阔的视野。", 2, "gaokao"],
  ["visual", "视觉的", "ˈvɪʒuəl", "Visual effect.", "视觉效果。", 2, "gaokao"],
  ["vital", "至关重要的", "ˈvaɪtl", "Vital role.", "关键作用。", 2, "gaokao"],
  ["volume", "量；音量；卷", "ˈvɒljuːm", "Sales volume.", "销售量。", 2, "gaokao"],
  ["voluntary", "自愿的", "ˈvɒləntri", "Voluntary work.", "志愿工作。", 2, "gaokao"],
  ["welfare", "福利", "ˈwelfer", "Social welfare.", "社会福利。", 2, "gaokao"],
  ["widespread", "广泛的", "ˈwaɪdspred", "Widespread use.", "广泛使用。", 2, "gaokao"],
  ["willing", "愿意的", "ˈwɪlɪŋ", "Willing to help.", "愿意帮忙。", 2, "gaokao"],
  ["wisdom", "智慧", "ˈwɪzdəm", "Conventional wisdom.", "传统智慧。", 2, "gaokao"],
  ["withdraw", "撤回；取款", "wɪðˈdrɔː", "Withdraw money.", "取钱。", 2, "gaokao"],
  ["witness", "目击者；见证", "ˈwɪtnəs", "Witness the event.", "见证事件。", 2, "gaokao"],
  ["workforce", "劳动力", "ˈwɜːrkfɔːrs", "Skilled workforce.", "熟练劳动力。", 3, "gaokao"],
  ["worldwide", "全世界的", "ˈwɜːrldwaɪd", "Worldwide fame.", "全球声誉。", 2, "gaokao"],
  ["worthwhile", "值得的", "ˌwɜːrθˈwaɪl", "Worthwhile effort.", "值得的努力。", 2, "gaokao"],
  ["yield", "产出；屈服", "jiːld", "Yield results.", "产生结果。", 2, "gaokao"],
  ["zone", "区域", "zoʊn", "Time zone.", "时区。", 2, "gaokao"]
];

async function seed() {
  const { initDb, run, get } = require('./db');
  await initDb();

  // 检查是否已有数据
  const count = get('SELECT COUNT(*) as cnt FROM words');
  if (count && count.cnt > 0) {
    console.log(`数据库已有 ${count.cnt} 个单词，跳过导入。`);
    return;
  }

  const stmt = `INSERT INTO words (word, translation, phonetic, example_sentence, example_translation, difficulty, list_type) VALUES (?, ?, ?, ?, ?, ?, ?)`;
  const insert = run; // 逐个插入

  let success = 0;
  for (const w of words) {
    try {
      run(stmt, [w[0], w[1], w[2] || '', w[3] || '', w[4] || '', w[5] || 1, w[6] || 'gaokao']);
      success++;
    } catch (err) {
      console.error(`导入失败: ${w[0]}`, err.message);
    }
  }

  const middle = words.filter(w => w[6] === 'middle').length;
  const gaokao = words.filter(w => w[6] === 'gaokao' || !w[6]).length;
  console.log(`✅ 导入完成！共导入 ${success} 个单词`);
  console.log(`  初中高频词: ${middle} 个`);
  console.log(`  高考核心词: ${gaokao} 个`);
  console.log(`  数据库位置: D:/word-remember/data.db`);
}

seed().catch(err => {
  console.error('导入失败:', err);
  process.exit(1);
});
